<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit34a23d4b011c4591b2957e8d7a7f5ce8
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit34a23d4b011c4591b2957e8d7a7f5ce8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit34a23d4b011c4591b2957e8d7a7f5ce8::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
